version: "2.4"

volumes:
  grafana-storage:

services:

  prometheus:
    image: prom/prometheus:v2.10.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    mem_limit: 200M
    restart: unless-stopped

  grafana:
    image: grafana/grafana:6.2.4
    container_name: grafana
    ports:
      - 3030:3030
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards/:/grafana/dashboards/
    mem_limit: 200M
    restart: unless-stopped

    cadvisor:
      image: google/cadvisor:v0.33.0
      container_name: cadvisor
      ports:
        - 8080:8080
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:ro
        - /sys:/sys:ro
        - /var/lib/docker/:/var/lib/docker:ro
        - /dev/disk/:/dev/disk:ro
      mem_limit: 200M
      restart: unless-stopped
    
    node-exporter:
      image: prom/node-exporter:v0.18.0
      container_name: node-exporter
      ports:
        - 9100
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
      command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      mem_limit: 200M
      restart: unless-stopped